=== Carolinabegara/TGI/xml/producto.dtd
<!ELEMENT producto (nombre,cantidad,tipo,unidades,precio,plantacion)> 
<!ATTLIST producto id CDATA #REQUIRED>
<!ELEMENT nombre (#PCDATA)> 
<!ELEMENT cantidad (#PCDATA) > 
<!ELEMENT tipo (#PCDATA)> 
<!ELEMENT unidades (#PCDATA)>
<!ELEMENT precio (#PCDATA) >  
<!ELEMENT plantacion (ultimo_regado,hectareas)>
<!ATTLIST plantacion id CDATA #REQUIRED>
<!ELEMENT ultimo_regado (#PCDATA) >  
<!ELEMENT hectareas (#PCDATA)>

=== Carolinabegara/TGI/xml/Producto.xml
<!DOCTYPE producto SYSTEM "Producto.dtd">
<producto id="0">
    <nombre>Patatas</nombre>
    <cantidad>100</cantidad>
    <tipo>Plantaci√≥n</tipo>
    <unidades>Kilos</unidades>
    <precio>1.0</precio>
    <plantacion id="0">
        <ultimo_regado>2021-05-20</ultimo_regado>
        <hectareas>1003.0</hectareas>
    </plantacion>
</producto>
